language: android
jdk: oraclejdk8
sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/daemon
  - $HOME/.gradle/native
  - $HOME/.gradle/wrapper

android:
  components:
  - platform-tools
  - tools
  - build-tools-28.0.2
  - android-28
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support
  - extra-google-google_play_services

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
install:
- bundle install --without documentation

script:
- ./gradlew --stacktrace :calendar:check :example:check detektCheck
- bundle exec danger --verbose
# - ./gradlew build connectedCheck
- ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew :clean :calendar:assembleRelease :calendar:bintrayUpload
  skip_cleanup: true
  dry_run: false
  on:
    branch: master
